version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=tentoken
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
    command: /start-dev.sh

  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=tentoken



  redis:
    image: redis:3.0

  # celeryworker:
  #   # https://github.com/docker/compose/issues/3220
  #   <<: *django
  #   depends_on:
  #     - redis
  #     - postgres
  #   ports: []
  #   command: /start-celeryworker-dev.sh
  #
  # celerybeat:
  #   # https://github.com/docker/compose/issues/3220
  #   <<: *django
  #   depends_on:
  #     - redis
  #     - postgres
  #   ports: []
  #   command: /start-celerybeat-dev.sh
