# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_asset_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='token_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Token id'),
        ),
    ]
