# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_waves'),
    ]

    operations = [
        migrations.AddField(
            model_name='waves',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
